<?php

namespace ContainerFjad3xf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCartService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Model\Cart' shared autowired service.
     *
     * @return \App\Model\Cart
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Model'.\DIRECTORY_SEPARATOR.'Cart.php';

        return $container->privates['App\\Model\\Cart'] = new \App\Model\Cart(($container->services['.container.private.session'] ?? $container->load('get_Container_Private_SessionService')), ($container->privates['App\\Repository\\ProductRepository'] ?? $container->load('getProductRepositoryService')));
    }
}
