<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFjad3xf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFjad3xf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFjad3xf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFjad3xf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFjad3xf\App_KernelDevDebugContainer([
    'container.build_hash' => 'Fjad3xf',
    'container.build_id' => '4ce310c4',
    'container.build_time' => 1693701279,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFjad3xf');
